import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import useSWR from "swr"
import useSWRMutation from 'swr/mutation'
const inter = Inter({ subsets: ["latin"] });
import { headers, dataBaseUrl, notionUsersBaseToken, usersDatabaseId } from "@/lib/variables";
import { notionDataFormatting } from "@/lib/notionDataFormatting";
import { useEffect, useState } from "react";
import { useRouter } from 'next/navigation'
import Cookies from 'js-cookie'
import useToken from "@/hooks/useLogin";
// const options = {
//   method: 'POST',
//   body: JSON.stringify({ request: 'whw3312@gmail.com'})
// }

export default function Home() {
  const token =useToken()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {<main className={`${styles.main} ${inter.className}`}>
        <h1>HOME</h1>
      </main>}
    </>
  );
}
